spring:
# Datasource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
# Hibernate properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Flyway Sql Migration
flyway:
  url: jdbc:postgresql://localhost:5432/postgres
  user: postgres
  password: postgres
